### PR TITLE
Fix console exception renderer

### LINKED ISSUE #420: ExceptionRenderer/Console switch to yellow font
https://github.com/atk4/core/blob/develop/src/ExceptionRenderer/Console.php

I guess something is wrong with this because it switch console font color to yellow after it finish dumping out text.
I expect it to switch back to previous text color as it was before dumping out this.

Is that possible?

### PR DESCRIPTION
**Pull request by DarkSide666**
fix #420

* fix missing reset codes
* add all colors as constants
* use unified text styling method
* replace PHP_EOL with \n because it works nicely in Windows console too
* add additional tests

### CODE REVIEW

File: src/ExceptionRenderer/Console.php [hunk 1]
```diff
@@ -134,12 +140,17 @@ protected function processPreviousException(): void
...
+    }
 
-        $this->output .= (string) (new static($this->exception->getPrevious(), $this->adapter, $this->exception));
-        $this->output .= <<<'EOF'
-            \e[1;31m--
-            \e[0m
-            EOF;
+    /**
+     * Style text with ASCII colors.
+     */
```
Comment (mvorisek) [inline src/ExceptionRenderer/Console.php]:
```suggestion
    /**
     * @param non-empty-list<self::FORMAT_*|self::COLOR_*> $formats
     */
```

Comment (mvorisek) [reply src/ExceptionRenderer/Console.php]: please avoid too much comments as this is even completely wrong, no human nor AI would be able to understand what it really does :)

File: tests/ExceptionTest.php [hunk 2]
```diff
@@ -46,6 +46,28 @@ public function testBasic(): void
...
+        self::assertStringNotContainsString('\e[', $ret);
+        self::assertMatchesRegularExpression('~\e\[0m(?!.*\e\[[0-9;]*m)~s', $ret); // reset colors at the end
+
+        $m->addMoreInfo('a1', 111);
+        $ret = $m->getColorfulText();
+        self::assertStringContainsString("\e[", $ret);
+        self::assertStringNotContainsString('\e[', $ret);
+        self::assertMatchesRegularExpression('~\e\[0m(?!.*\e\[[0-9;]*m)~s', $ret); // reset colors at the end
+
+        $m->addSolution('Simple solution');
```
Comment (mvorisek) [inline tests/ExceptionTest.php]: add all at once, text would be then deduplicated by itself ;-)

Comment (DarkSide666) [reply tests/ExceptionTest.php]: Not exactly. First I test simple exception, then test with added additional info and then with added solution info.

File: src/ExceptionRenderer/Console.php [hunk 3]
```diff
@@ -134,12 +142,17 @@ protected function processPreviousException(): void
...
 
-        $this->output .= (string) (new static($this->exception->getPrevious(), $this->adapter, $this->exception));
-        $this->output .= <<<'EOF'
-            \e[1;31m--
-            \e[0m
-            EOF;
+    /**
+     * @param non-empty-list<self::FORMAT_*|self::COLOR_*|self::BG_COLOR_*> $formats
+     */
+    private static function text(string $text, array $formats = []): string
```
Comment (mvorisek) [inline src/ExceptionRenderer/Console.php:154]:
```suggestion
    private static function text(string $text, array $formats): string
```

File: tests/ExceptionTest.php (hunk 2 above)
Comment (mvorisek) [reply tests/ExceptionTest.php]: Ahh, I know what you mean.

We can newly assert format tokens are in pairs :) - see what I meant the test is too specific..

Comment (DarkSide666) [reply tests/ExceptionTest.php]: Sorry I don't get what you want to do differently here :)
Maybe I'm to sleepy :)
